FROM mysql:8.0.3

LABEL maintainer="Carlos Thurber B."

# fixing permissions
RUN usermod -u 1000 mysql

EXPOSE 3306 

COPY ./my.cnf /etc/mysql/conf.d
COPY ./myDB.sql docker-entrypoint-initdb.d/init.sql
