FROM php:7.0-apache 

MAINTAINER Carlos Thurber B.

RUN docker-php-ext-install mysqli

COPY ./src/phpunit /var/www/html/phpunit

RUN /bin/bash -c 'chmod +x /var/www/html/phpunit'

WORKDIR /var/www/html/



